# Generated by Django 5.2 on 2025-04-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='imgUrl',
            field=models.CharField(default='#', max_length=1000),
        ),
    ]
