# Generated by Django 5.2 on 2025-04-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCursos', '0003_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='numintegrantes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
