# Generated by Django 5.2 on 2025-04-29 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCursos', '0004_grupo_numintegrantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problemas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codeforcesId', models.IntegerField()),
                ('codeforcesIndex', models.CharField(max_length=10)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionCursos.grupo')),
            ],
        ),
    ]
